apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "basic-rails.name" . }}
    chart: {{ template "basic-rails.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
